# Generated by Django 4.0.4 on 2022-05-18 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaddress',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='myaddresss', related_query_name='myaddress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myaddress',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
